georchestra/mapstore2-cadastrapp

js/extension/epics/cadastrapp.js
js/extension/epics/layerSync.js
js/extension/epics/mapSelection.js
js/extension/selectors/cadastrapp.js
webpack.config.js

This PR provides selection of features for point/line/polygon. 
- #9 
-  #10 
- #11

#9 #10 #11 map selection

---

.gitignore
js/extension/actions/cadastrapp.js
js/extension/components/modals/PreferencesModal.jsx
js/extension/components/style/StyleEditor.jsx
js/extension/constants.js
js/extension/epics/layerSync.js
js/extension/plugins/__tests__/testUtils.js
js/extension/plugins/cadastrapp/toolbar/Preferences.jsx
js/extension/plugins/cadastrapp/toolbar/RequestLanding.jsx
js/extension/plugins/cadastrapp/toolbar/__tests__/Preferences-test.jsx
js/extension/reducers/__tests__/cadastrapp-test.js
js/extension/reducers/cadastrapp.js
js/extension/selectors/cadastrapp.js
package.json

#20: Add preferences modal to configure the plot search result styles

---

js/extension/components/PlotSelection.jsx
js/extension/components/misc/ConfirmButton.jsx
js/extension/components/plot/PlotSelectionToolbar.jsx
js/extension/epics/events.js
js/extension/plugins/cadastrapp/PlotSelection.jsx
js/extension/selectors/cadastrapp.js

This PR add "zoom to list" option, and fixes minor issues

#9 implemented zoom for empty selection. Minor fixes

---

js/extension/api/__tests__/api-test.js
js/extension/api/api.js
js/extension/api/index.js
js/extension/components/forms/Address.jsx
js/extension/components/forms/ProprietaireCombo.jsx
js/extension/components/forms/Reference.jsx
js/extension/components/forms/RoadCombo.jsx
js/extension/components/forms/SearchCombo.jsx
js/extension/components/forms/User.jsx
js/extension/components/lists/ReferenceRow.jsx
js/extension/components/search/OwnersSearch.jsx
js/extension/components/search/PlotSearch.jsx
js/extension/constants.js
js/extension/epics/search.js
js/extension/hooks/useFormState.jsx
js/extension/plugins/cadastrapp/SearchSection.jsx
js/extension/utils/validation.js

Fixed clear and improved UI for plot search.
Add User part of owner search #16

Some fixes for search tools #15. Initial work for Owner search

---

js/extension/api/api.js
js/extension/components/forms/OwnerId.jsx
js/extension/components/forms/OwnerLot.jsx
js/extension/components/lists/StrList.jsx
js/extension/components/search/OwnersSearch.jsx
js/extension/constants.js
js/extension/epics/search.js
js/extension/utils/validation.js

This PR implements owner search (by User or birth name, OwnerId, Lot). 
Missing #32, that has a dedicated issue for that

#16: Owner Search

---

js/extension/api/api.js
js/extension/components/plot/BundleInformationModal.jsx
js/extension/components/plot/PlotSelectionToolbar.jsx
js/extension/plugins/cadastrapp/PlotSelection.jsx

This PR adds the export functionalities to plot selection (export drop down menu).

#12 Implemented exports

---

js/extension/components/forms/Lot.jsx
js/extension/components/forms/OwnerLot.jsx

Fixes issues with csv files on windows (there was a filter for "text/csv" mime type, but windowe associate to csv an "excel" mime type. I solved it by adding csv extension.

#49 Fixed Lot files

---

js/extension/cadastrapp.css
js/extension/components/forms/Lot.jsx
js/extension/components/forms/OwnerLot.jsx
js/extension/components/lists/ReferencesList.jsx
js/extension/components/table/MultilineHeaderTable.jsx
js/extension/components/table/PlotsSelectionTable.jsx
js/extension/epics/search.js
js/extension/reducers/cadastrapp.js

#37. Sorting plot selection, comboboxes overflow, autoopen plot + minor

#37. Sorting plot selection, comboboxes overflow, autoopen plot + minor

---

js/extension/actions/cadastrapp.js
js/extension/epics/layerSync.js
js/extension/epics/mapSelection.js
js/extension/epics/setup.js
js/extension/reducers/cadastrapp.js

This PR contains 
- #48 allow to close/repoen
- #37 solves issues about catalog and toolbar visibility
- Zoom offset issues due to layout.

#48 Keep same state #37 Solve toolbar/catalog issues

---

js/extension/api/api.js
js/extension/components/landedproperty/Content.jsx
js/extension/components/landedproperty/Modal.jsx
js/extension/epics/mapSelection.js

#36 Solved issue with printed part

#36 Fixed proprietaires in property print page

---

README.md
assets/index.json
js/extension/actions/cadastrapp.js
js/extension/components/modals/Preferences.jsx
js/extension/components/modals/__tests__/Preferences-test.js
js/extension/plugins/cadastrapp/MainToolbar.jsx
js/extension/plugins/cadastrapp/toolbar/Preferences.jsx
js/extension/reducers/cadastrapp.js
localConfig.json

This PR adds defaultStyle config option for Preferences
##Issue
#47 
Default style config option is used for preferences when present

#47: Default styles configuration

---

js/extension/cadastrapp.css
js/extension/components/forms/SearchCombo.jsx
js/extension/components/lists/ReferenceRow.jsx
js/extension/components/request/RequestObjectItem.jsx
js/extension/components/request/searchCombos/ProprietaireComboList.jsx
js/extension/components/request/searchCombos/SectionCombo.jsx

This PR adds possibility to display the combox/dropdown list/select field to drop up the menu list
##Issue
#18 

#18: Request object select menu drop up

---

.github/workflows/cadastrapp.yml

enable github actions to build and upload Cadastrapp.zip artifact

---

README.md
js/extension/cadastrapp.css

Improved responsiveness of screen size for the right panel. 
Updated readme.

Minor fixes on scrollbars and readme update

---

js/extension/components/owners/Modal.jsx
js/extension/components/table/OwnersListTable.jsx

Fixed localization in Owners window

Fixed localization in owners window

---

js/extension/components/forms/User.jsx
js/extension/components/request/RequestObjectItem.jsx

This issue was caused by a refactor when re-using PropertySelector in RequestForm. 
Restored original functionality.

#68 fixed regression with birthsearch due to reuse partial refactor

---

assets/translations/data.fr-FR.json

improve french translations

---

js/extension/actions/cadastrapp.js
js/extension/components/popup/__tests__/PopupViewer-test.js
js/extension/epics/__tests__/mapSelection-test.js
js/extension/epics/__tests__/setup-test.js
js/extension/epics/mapSelection.js
js/extension/epics/search.js
js/extension/plugins/cadastrapp/toolbar/__tests__/Preferences-test.jsx
js/extension/reducers/__tests__/cadastrapp-test.js
js/extension/reducers/cadastrapp.js

fixed unit tests

---

js/extension/constants.js

modify default selection colors

---

js/extension/components/information/Plot.jsx

Fixed the wrong value in information modal, Plot tab.

#84 fixed wrong label

---

js/extension/epics/layerSync.js

This PR resync the current selection layer when the tab changes

#96 ReSync selection on new tab

---

js/extension/components/landedproperty/Modal.jsx
js/extension/epics/mapSelection.js
js/extension/plugins/cadastrapp/LandedProperty.jsx
js/extension/selectors/cadastrapp.js

With this PR the application retrieves feature from uf layer configured, when possible (map selection, access from plot selection do not allow this feature, as in the original application).

#67 Retrive feature from uf layer when possible

---

assets/translations/data.fr-FR.json

Fixed a missing comma in the FR translations json

Fixed FR json

---

js/extension/utils/__tests__/configuration-test.js
js/extension/utils/configuration.js

Sort by index instead of using Json order fro background maps

#88 sort backgrounds by index

---

assets/translations/data.en-US.json
assets/translations/data.fr-FR.json
assets/translations/data.it-IT.json

Improve some strings

---

assets/translations/data.en-US.json
assets/translations/data.fr-FR.json
js/extension/cadastrapp.css
js/extension/components/information/Plot.jsx
js/extension/components/plot/ExportPlotsAsPDFModal.jsx
js/extension/components/plot/PlotSelectionToolbar.jsx
js/extension/selectors/cadastrapp.js

This PR adds commit to export all plots selected as a single PDF 
##Issue
#135 
User can export plots selection as single PDF from plot selection toolbar

#135: Plot export to PDF in batch

---

js/extension/constants.js

Fix helpUrl for all occurences

---

js/extension/components/table/OwnersTable.jsx
js/extension/components/table/PlotsSelectionTable.jsx

This PR adds way type info to addresses
#146 
The address will now display way type info

#146: Update address way type info

---

js/extension/components/information/building/Description.jsx
js/extension/components/landedproperty/Content.jsx
js/extension/components/owners/Modal.jsx
js/extension/components/popup/PopupViewer.jsx

Added eslint ignore for variables not in camelcase where such variables can occur (processing API data)
- [] Tests for the changes have been added (for bug fixes / features)
[#52](https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/issues/52)
As per description

Ignore variables not in camelcase

---

assets/translations/data.en-US.json
assets/translations/data.fr-FR.json
js/extension/actions/cadastrapp.js
js/extension/components/plot/PlotSelectionToolbar.jsx
js/extension/epics/__tests__/events-test.js
js/extension/epics/cadastrapp.js
js/extension/epics/events.js
js/extension/plugins/cadastrapp/PlotSelection.jsx
js/extension/utils/__tests__/download-test.js
js/extension/utils/download.js

Exporting selected plots into annotation

Exporting selected plots into annotation

---

.github/workflows/cadastrapp.yml

cf georchestra/mapstore2-georchestra#545 - @gaetanbrl for me just changing this is enough.

build additional unminified extension in gh actions

---

README.md
js/extension/cadastrapp.css
js/extension/components/information/InformationPanelContainer.jsx
js/extension/plugins/cadastrapp/Header.jsx
js/extension/plugins/cadastrapp/Main.jsx

This PR updates the color palette with geOrchestra theme [variable](https://github.com/georchestra/mapstore2-georchestra/blob/master/themes/default/variables.less)

Align color palette with geOrchestra theme variable
