georchestra/mapstore2-cadastrapp

README.md, js/__tests__/app-test.js, js/extension/actions/cadastrapp.js, js/extension/components/plot/PlotSelectionToolbar.jsx, js/extension/epics/cadastrapp.js, js/extension/epics/events.js, js/extension/epics/setup.js, js/extension/plugins/cadastrapp/PlotSelection.jsx, js/extension/reducers/cadastrapp.js, js/extension/selectors/cadastrapp.js
This adds an initial implementation of #9 and provides some fixes for setup/tear-down of the panel.
The finalization of #9 requires to add to MapStore some layout info, in order to zoom to Extent with the correct right offset (actually hardcoded in layout epic)
I'm going to do a proposal for this in a MapStore issue
=> Initial implementation of zoom to selection

assets/index.json, assets/translations/data.en-US.json, assets/translations/data.fr-FR.json, assets/translations/data.it-IT.json, js/extension/constants.js, js/extension/plugins/cadastrapp/Main.jsx, js/extension/plugins/cadastrapp/MainToolbar.jsx, js/extension/plugins/cadastrapp/toolbar/Help.jsx, js/extension/plugins/cadastrapp/toolbar/__tests__/Help-test.jsx, localConfig.json
This PR allows help url to be configured for the cadastrapp plugin
##Issue
#19 
- The help url can be configured via local config
- Url can also be configured from context creator
=> #19: Configure plugin help url

js/extension/components/information/PropertiesRadio.jsx
Points 1 and 4 of #43 already fixed in previous commits. This changes fix also points 2 and 3, both caused by putting the same  comptecommunal  multiple times in the request. The original app removed duplicates before to download.
In case of this duplication PDF simply duplicates the output while csv fails with an error and this is the reason of the different results.
=> #43 remove duplicated comptecommunal in exports

README.md, assets/index.json, js/extension/cadastrapp.css, js/extension/components/modals/Preferences.jsx, js/extension/components/plot/PlotSelectionToolbar.jsx, js/extension/components/search/CoownershipSearch.jsx, js/extension/plugins/cadastrapp/MainToolbar.jsx, js/extension/plugins/cadastrapp/toolbar/Preferences.jsx, js/extension/plugins/cadastrapp/toolbar/SelectionTools.jsx
- Set Preference Window as modal
- #47 make foncier option work. 
- #49 add docUrl to the extension 
- minor fix to co-owners search. Now owners window shows also in co-owners, when write only text, as well as in the owners search. If something is written in plotId, it takes priority
=> #20 preference is now draggable. #47 foncier, #49 docUrl

js/extension/components/information/FiscalSubDivisions.jsx, js/extension/components/information/Owners.jsx, js/extension/components/owners/Modal.jsx, js/extension/components/table/BuildingsTable.jsx
#71 is due to an invalid rowClick event when clicking on header (in tables that intercept rowClick event). Fixed preventing the event to be used when rowIdx < 0 (header idx is `-1`)
=> #71: Prevent errors due to click events on header row

README.md, assets/index.json, js/extension/enhancers/init.jsx, js/extension/plugins/Extension.jsx
Adds option `openOnLoad` to plugin configuration. If true, the panel will auto-open when rendered.
=> #72. Add option to open on startup

js/extension/components/information/Plot.jsx
There was some missing code to send the effective base map selected to the server in plot export. This PR solves this problem.
=> #89: Use selected basemap for plot export

js/extension/components/modals/Request.jsx
Now when limit is reached, the message is shown on list, as when you try to do too much requests at the same time.
=> #101 show max request message when the limit is 0

js/extension/components/plot/PlotSelectionToolbar.jsx
This PR fixes export button enabled when no plot selected, for non CNIL user
##Issue
#114
The export button will be enabled only when data present and at least one plot selected
=> #114: Plot selection export button fix for non CNIL users

assets/translations/data.en-US.json, assets/translations/data.fr-FR.json, assets/translations/data.it-IT.json, build/extension/commons.js, build/extension/prod-webpack.config.js, build/extension/webpack.config.js, js/extension/cadastrapp.css, js/extension/components/modals/Welcome.jsx, js/extension/plugins/cadastrapp/Main.jsx, js/extension/plugins/cadastrapp/MainPanel.jsx, localConfig.json, package.json, webpack.config.js
This PR adds commit to display data freshness of the cadastrapp and land plan and along with build information
##Issue
#113
The Cadastrapp plugin welcome area will display the dates of the cadatrapp and land plan from configuration along with the build information
=> #113: Info on data freshness

js/extension/cadastrapp.css
#125 
Applied changes to CSS (for square-button, I applied CSS suggested only to side-bar)
Final result (window height 800px):
=> #125 Adjust side bar for smaller screens

js/extension/components/search/OwnersSearch.jsx, js/extension/epics/search.js
This PR shows the user list when the selection returned anyway more than one result, to avoid ambiguity.
See #123
=> #123 Always show owner selection when ambiguous

js/extension/components/table/PlotsSelectionTable.jsx
This PR reorders the column of Plot selection as per mapfish application
#128
Plot selection column order change
=> #128: Plot selection column order change

js/extension/epics/__tests__/setup-test.js, js/extension/epics/setup.js
This PR removes the marker from the map, if present. as for #134
This happens when the feature info is not present but active because of this reason: https://github.com/geosolutions-it/MapStore2/issues/7111
=> #134: remove the marker when cadastrapp opens

package.json
Since https://github.com/geosolutions-it/MapStore2/issues/7294 raised in
some of our plateform. I just changed the name of the app to
"CadastrappExtension" in order to avoid clash between mapstore plugins.
=> Change the name of the extension in package.json

js/extension/api/api.js, js/extension/components/forms/MunicipalityCombo.jsx, js/extension/components/forms/ProprietaireCombo.jsx, js/extension/components/forms/RoadCombo.jsx, js/extension/components/forms/SearchCombo.jsx, js/extension/components/request/searchCombos/ProprietaireComboList.jsx, js/extension/constants.js, js/extension/selectors/cadastrapp.js
This PR adds fix to search by commune and libcom based on search value. Use cadastrapp service configuration for minCharToSearch value
#144 
- Delegate search by commune and libcom based on search value
- `minCharToSearch` is used from cadastrapp configuration
=> #144: Search by commune and libcom

js/extension/cadastrapp.css
This PR allows possibility to select texts from react grid cells
#141 
User can now `click and drag/double click` on grid cell to select a text 
=> #141: Allow text selection from react grid cell

js/extension/utils/download.js
Link to https://github.com/georchestra/cadastrapp/issues/615 and #143 
Tested on gis.jdev.fr environnement
=> remove duplicated quote to remove underscore create by browser

assets/index.json, js/extension/actions/cadastrapp.js, js/extension/cadastrapp.css, js/extension/components/misc/panels/DockContainer.jsx, js/extension/epics/mapSelection.js, js/extension/epics/setup.js, js/extension/plugins/Extension.jsx, js/extension/plugins/cadastrapp/Main.jsx, js/extension/selectors/maplayout.js
This PR applies several changes and improvements to the cadastrapp to make it compatible with the updated MapStore layout (https://github.com/geosolutions-it/MapStore2/issues/8086)
1.  Extension will properly update map layout when cadastrapp panel is open. It will apply additional offset to the panel if sidebar exists.
2.  Annotations and cadastrapp tools can be open at the same time, but only one of them can perform drawing operations at a time. When cadastrapp selection tool is toggled on - geometry edit session in annotations will be cancelled, unsaved geometry will disappear. If annotations starts drawing geometry while cadastrapp has selection tool active - it will be automatically toggled off.
3. Cadastrapp panel will close when feature editor panel at the bottom is open.
4. …
=> Applying necessary changes to cadastrapp to support MapStore layout changes

js/extension/components/information/Buildings.jsx
Fixes #168, might not be the best fix but it works here, no more 400 errors, when opening the info form on a plot without buildings the building tag show "no data to display", and properly displays the building if there's one on the plot.
=> only call getBatiments if there are buildings on the plot (#168)

js/extension/components/lists/ReferenceRow.jsx, js/extension/components/table/PlotsSelectionTable.jsx
fixes #164, supersedes #165
there might be more occurences where `ccopre` is missing.
@MaelREBOUX ?
=> Properly prefix section name ccosec with ccopre field

README.md
Allows me to debug features that are only availabled to logged-in users with non-defaults cadastrapp rights.
@gaetanbrl @jusabatier @tkohr @fvanderbiest might be helpful to you.
=> Add details on how to properly authenticate against mapstore/cadastrapp via headers when running in dev mode

js/extension/cadastrapp.css
This PR updates the style override that was reducing the dropdown menu width. This issue was impacting all container applications using the extension
https://github.com/geosolutions-it/MapStore2/issues/10693
=> Style update to fix dropdown menu width

js/extension/cadastrapp.css, js/extension/components/search/PlotSearch.jsx, js/extension/plugins/cadastrapp/MainToolbar.jsx, js/extension/plugins/cadastrapp/toolbar/SelectionTools.jsx
Modify selection tools from main toolbar to search panel.
Should the uf search button also be moved as mentioned in [this comment](https://github.com/georchestra/mapstore2-cadastrapp/issues/197#issuecomment-2545237508) ?
=> ISSUE-197 - Icon grouping for map selection

js/extension/cadastrapp.css, js/extension/components/PlotSelection.jsx, js/extension/components/lists/ReferencesList.jsx, js/extension/components/lists/StrList.jsx, js/extension/components/search/CoownershipSearch.jsx, js/extension/components/search/OwnersSearch.jsx, js/extension/components/search/PlotSearch.jsx, js/extension/components/search/SearchButtons.jsx, js/extension/components/table/PlotsSelectionTable.jsx, js/extension/plugins/cadastrapp/PlotSelection.jsx, js/extension/reducers/cadastrapp.js
Multiple changes to the parcel search interface:
- the ‘+’ button is now placed after the tabs used to search for plots, like a web browser.
- tab deletion is now done by a cross on each tab. The dustbin has been removed.
- the ‘search’ and ‘delete’ buttons have been grouped together in the plot search block to avoid confusion with the plot selection block below. 
These changes have been reflected in the search for owners and co-owners to maintain the overall consistency of cadastrapp.
Tested in integration.
Mapstore 2023.02
Node 16.20.2
=> ISSUE-198 - Reorganization of the plot of land interface, in particular for waste garbage cans
